# -*- coding: utf-8 -*-
"""11일차

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yrrZ5Gxssc7qHRqd9AkQMLqiMgF0dLcl
"""

f = open('ex_memo.txt','w')
students = ['김철수', '최영', '한석규', '김태희']
for student in students:
    msg = student
    f.write(msg+"\n")
f.close()



file = open('hello.txt', 'w')
file.write('Hello, world!')
file.close()

f = open('test.txt','a', encoding='UTF-8')

for i in range(4,10):
    data = "%d 번째 줄입니다. \n"%i
    f.write(data)
f.close()

lines = ['안녕하세요.\n', '파이썬\n', '코딩 도장입니다 \n']

with open('hello.txt', 'w') as file:
    file.writelines(lines)
file.close()

f = open("hz.txt", "a", encoding='UTF-8')
f.writelines(["\n홈짱닷컴", "\nHomzzang.com"])
f.close()

f = open('ex_memo.txt', 'w')
students = ['김철수', '최영', '한석규', '김태희']
for student in students:
    msg = student
    f.write(msg+"\n")
f.close()

f = open('ex_memo2.txt', 'w')
students = ['김철수', '최영', '한석규', '김태희']
f.writelines('\n'.join(students))
f.close

f = open('ex_memo.txt', 'r')

print('\n1. read()')
print(f'위치 : {f.tell()}')
s1 = f.read(1)
print(s1)
print('\n2. readline()')
print(f'위치 : {f.tell()}')
s2 = f.readline()
print(s2)
print('\n3. readlines()')
print(f'위치 : {f.tell()}')
s3 = f.readlines()
print(s3)

f = open(r'text.txt')
#f = open('test.txt', 'r')
text = f.read()
print(text)

f.close()

f = open(r'test.txt')
line = f.readline()
line = line.strip()
print(line)
line = f.readline()
line = line.strip()
print(line)
line = f.readline()
line = line.strip()
print(line)

f.close()

f = open(r'text.txt')

print('\n4. seek(0), readline()')

f.seek(0)
print(f'위치 : {f.tell()}')

s4 = f.readline()
print(s4)

f.close()