# -*- coding: utf-8 -*-
"""4일차

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nLmUUyWlJbC5hGsUu6UCJarTlkMKjSeB
"""

a =4
b =3

print(a/b)

c=1
d=2
print(c/d)

e=7
f=3
print(e//f)
print(e%7)
print(e**f)

quotient,remainder =divmod(5,2)
print(quotient,remainder)

a=11+2
b=12-2
c=13*2
d=14/2
e=15**2
f=16//2
g=17%3

print(a,b,c,d,e,f,g)

i=3
i+=3
print(i)
i-=3
print(i)
i*=2
print(i)
i/=2
print(int (i))
i//=2
print(i)
i%=2
print(i)

a = 10
b = 3
print("10 == 3 =>", a == b)
print("10 != 3 =>", a != b)
print("10 > 3 =>", a > b)
print("10 >= 3 =>", a >= b)
print("10 < 3 =>", a < b)
print("10 <= 3 =>", a <= b)
print()

a=13
print(bin(a))
print(hex(a))

a=13
b=9
print(bin(a))
print(bin(b))
print(bin(a&b))
print(a&b)

a=13
b=9
print(bin(a))
print(bin(b))
print(bin(a|b))
print(a|b)

a=13
b=9
print(bin(a))
print(bin(b))
print(bin(a^b))
print(a^b)