# -*- coding: utf-8 -*-
"""7일

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CDWS5t-73v2rnCRGQDJbkwv77Dld6NUY
"""

a = 'I Love Python'
print( len(a))

name = 'BlockDMask'
phone = '010 2351 5610'
address = 'korea'
print(len(name))
print(len(phone))
print(len(address))

a = [1, 2, 3]
print(min(a))

b = 'cBlockDMask'
print(min(b))

c = 1
print(min(c))

d = (6, 5, 4, 2)
print(min(d))

e = [3,4,5, 'a','b','c']
print(min(e))

d = (6, 5, 4, 2)
print(min(d))

e = [3,4,5, 'a','b','c']
print(min(e))

a = [1,2,3]
b = [1,2,4]
print(min(a,b))

c = 'CC'
d = 'BA'
print(min(c,d))

e = [2, 3, 4]
f = [2, 2, 2, 2, 2]
i = [9, 8, 7, 6, 5]
j = [1]
k = ['a']
print(min(e, f, i, j, k))

myString = "everdevel"
print(myString.count('e'))

a = 'BlockDMask'

print('#1 a.count("Ma")')
print(a.count('Ma'))
print('#2 a.count("ck")')
print(a.count("ck"))

str = "BlockDMask"
print(f"str : {str}\n")

# find 에제1 LMJ
print("1. str.find('찾을문자')")
result1 = str.find('B')
print(result1)

#문자가 있는 경우
result2 = str.find('Z')

#문자가 없는 경우
print(f"str.find('B') : {result1}")
print(f"str.find('Z') : {result2}")

result3 = str.find('ask')
print(f"str.find('ask') : {result3}")

str = "BlockDMask"
print(f"str : {str}\n")

result4 = str.find('kkk')
# 문자열이 없는 경우
print(f"str.find('kkk') : {result4}")

print("2. str.find('찾을 문자', 시작index)")
result5 = str.find('o')
result6 = str.find('o', 5)
print(f"str.find('o') : {result5}")
print(f"str[5] : {str[5]}")
print(f"str.find('o', 5) : {result6}")

str = "BlockDMascleark Blog.";
print(f"str : {str}\n")

print("1. str.find('찾을문자')")
result1 = str.rfind('B')
print(f"str.rfind('B') : {result1}")

str = 'Hello world, Python!'

if str.startswith('Hello'):
    print('It starts with Hello')
if not str.startswith('Hello'):
    print('It does not start with Hello')


print(str.startswith('Hello'))
print(str.startswith('Python'))

str = 'Hello world, Python!'

print(len(str))

if str.startswith('Hello'):
    print('It starts with Hello')
if not str.endswith('Hello'):
    print('It does not start with Hello')


print(str.startswith('Hello',1))
print(str.endswith('Python!',1,20))

str = "this is string example....wow!!!"

print(len(str))
suffix = "wow!!!"
print(str.endswith(suffix))
print(str.endswith(suffix,20))

suffix = "is"
print(str.endswith(suffix, 2, 4))
print(str.endswith(suffix, 2, 7))

nums_list = [1,2,3,3,3,4,5,6,7]
nums_tuple = (1,2,3,4,4,5,5,6)
nums_set = {1,2,3,5,6,7,8}

print(nums_list.index(6))
print(nums_list.index(3))

print(nums_tuple.index(2))
print(nums_tuple.index(5))

print(nums_set.index(2))
print(nums_set.index(5))

text = 'Welcome to Codetorial'

pos_Code_last = text.rindex('Code')
print(pos_Code_last)

pos_code_last = text.rfind('code')
print(pos_code_last)

pos_Code_last = text.rindex('code')
print(pos_Code_last)