# -*- coding: utf-8 -*-
"""8일차

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jDcvVu3kuEg7TwBvT3J5SBGia1etJgEH
"""

text1 = "네이스123"
text2 = "1231231"
text3 = "!@#"
text4 = "!#1234"
text5 = "nice"
text6 = "nicew1234"
print(text1.isalnum())
print(text2.isalnum())
print(text3.isalnum())
print(text4.isalnum())
print(text5.isalnum())
print(text6.isalnum())

a = "BlockDMask"
b = "1234Blog"
c = "1231231"
d = "-234"
e = "1.23"
f = "3"
g = '2/3'
h = "0"
print(f"'{a}' .isdigit() : {str.isdigit(a)}")
print(f"'{b}' .isdigit() : {str.isdigit(b)}")
print(f"'{c}' .isdigit() : {str.isdigit(c)}")
print(f"'{d}' .isdigit() : {str.isdigit(d)}")
print(f"'{e}' .isdigit() : {str.isdigit(e)}")

a = '123456789'
print(a.isdigit())
print(a.isdecimal())
print(a.isnumeric())
print('\n\n')
x ='3'
print(x)
print(x.isdigit())
# True
print(x.isdecimal())
# False
print(x.isnumeric())

a = "I Love Python"

print(a.islower())
print(a.islower())
print(a.upper())
print(a.lower())

print('\n\n')

str = "This is string example...wow!!!"
print(str.islower())
print(str.upper())

str = "this is string example...wow!!!"
print(str.islower())

str = "This is string Example...Wow!!!"
print(str.swapcase())

str = "THIsis stRINg eXample...Wow!!!   1234"
print(str.swapcase())

str = "This Is String Example...Wow!!!"
print(str.istitle())

str = "This is string example...Wow!!!"
print(str.istitle())
print(str.title())

print('hello world!'.capitalize())
print('HELLO WORLD!'.capitalize())