# -*- coding: utf-8 -*-
"""9일차

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H5Z_Am6QqZVva9cA5G3cf1PehCmMRRL5
"""

a='   test'
b='~~.test.~~ '
c='~test!'

print(a.lstrip())
print(b.lstrip())
print(c.lstrip())

a='   test'
b='~~.test.~~ '
c='~test!'

print(a.rstrip())
print(b.rstrip())
print(c.rstrip())

text=' water boils at 100 degrees '
print('[' + text.rstrip() + ']')
print('[' + text.lstrip() + ']')
print('[' + text.strip() + ']')

text = '000000000Water boils at 100 degress 000'
print(text.lstrip('0'))
print(text.rstrip('0'))
print(text.strip('0'))

print('\n\n')
text = ",,,,,,123...water...pp"
print(text.lstrip(',123.p'))
print(text.rstrip(',123.p'))
print(text.strip(',123.p'))

txt="   HZ     "
x=txt.isspace()
print(x)

sentence= input("문자열을 입력하시오: ")
table ={ "알파벳" :0,"숫자" : 0, "빈칸" : 0}

for i in sentence :
    if (i.isalpha()):
        table["알파벳"] += 1
    elif (i.isdigit()) :
              table["숫자"] += 1
    elif (i.isspace()) :
             table["빈칸"] += 1
print(table)

txt="        "
x=txt.isspace()
print(x)

sentence= input("문자열을 입력하시오: ")
table ={ "알파벳" :0,"숫자" : 0, "빈칸" : 0}

for i in sentence :
    if (i.isalpha()):
        table["알파벳"] += 1
    elif (i.isdigit()) :
              table["숫자"] += 1
    elif (i.isspace()) :
             table["빈칸"] += 1
print(table)

### 우측 정렬 예시
s='가나다라'
n=7

answer = ''
for i in range(n-len(s)): #문자열의 앞을 빈 문자열로 채우는 for문
    answer += ' '
answer += s

print(answer)

print(s.ljust(n))
print(s.center(n))
print(s.rjust(n))

s = "aa.bb.cc.BlockDMask.ee.ff.gg.python.example"
print(s)

r0 = s.split()
r1 = s.split('.',3)
r2 = s.split(sep='.', maxsplit=4)
r3 = s.split('.', maxsplit=3)
print(f"\ns.split()\n{r0}")
print(f"\ns.split('.',4)\n{r1}")
print(f"\ns.split(sep='.', maxsplit=3)\n{r2}")
print(f"\ns.split('.', maxsplit=3)\n{r3}")

txt ="홈짱닷컴\nHomzzang.com"
x= txt.splitlines()
print(x)

txt = "123, 456, 789, 999"

print(txt.replace("," , ""))
print(txt.replace(",","!",1))
print(txt.replace(",","!",2))
print(txt.replace(",","!",3))

a = ['a', 'b', 'c', 'd', '1', '2', '3']
 print(a)

 result1 = "".join(a)
 print(result1)

print( "3".zfill(3))
print( "s1".zfill(4))

a = 'abc'

print(a.rjust(10))
print(a.rjust(10, '#'))

print(a.ljust(10))
print(a.ljust(10, '*'))

print('\n')

b = 'def'
print(b.ljust(15))
print(b.ljust(15, 'k'))